### ISSUE TITLE
Some errors on Readme.md and script

### ISSUE THREAD

**Issue by crazycoder1999** [anjishnu/ask-alexa-pykit#12]
Hi,
 I’ve found some problems on your Readme.md, point 2:

_$ python -m ask.intent_schema -i FILEPATH _ <--- Wrong Script!

is instead:

_$ python -m ask.generate_intent_schema -i intents_

On step6 you should add to "select [Virgina] on the top right", the other amazon's state doesn't have alexa skill available.

On the **generate_intent_schema**, if you select "0 Exit program" option, it fails brutally :)
1. Exit program
   0
   Schema created:
   Traceback (most recent call last):
   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
     "__main__", fname, loader, pkg_name)
   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
     exec code in run_globals
   File "/Users/dega1999/Programming/Alexa/ask-alexa-pykit/alexa/ask/generate_intent_schema.py", line 91, in <module>
     print (json.dumps(output, indent=2))
   NameError: name 'output' is not defined

BTW, I have succesfully loaded a new alexa skill, very fast, thanks to your work!
Thanks you!

**Comment by anjishnu** [comment]
Hi. For your first problem I think you may be using an older version of the program - the README on this page is for version 0.5.1 of the pykit. An older version used to use the ask.generate_intent_schema script. 

Thanks for calling out the other two bugs - I'll fix them soon.

**Comment by anjishnu** [comment]
The latest version of the code does not have any of these bugs.
