### ISSUE TITLE
The included basic example

### ISSUE THREAD

**Issue by jrlandau** [anjishnu/ask-alexa-pykit#14]
Step 3a for the basic example says "go to 3b", but I don't understand what 3b means in this context.  I don't see an utterance text file.  

Perhaps because of this, when I complete all the steps, I do not understand what should happen. There are no Intent Schema or Sample Utterances in the Interaction Model.

**Comment by issachan** [comment]
I'm in a similar place. I have it all almost working, but for 3B, I cannot generate an utterances.txt. 
what do I put in place of "INTENT_SCHEMA" in python -m ask.generate_training_data -i INTENT_SCHEMA -o E:...

JR What you should get (if I'm not mistaken), is the sample stuff you need to configure the skill. Right now you have all the code you need to make a function that'll work. This function can generate it's own Alexa instructions that will invoke the function for the sample. So, it comes with a short intent schema - "sample_intent_schema.json" and should generate an utterances file. Both of those would be pasted into your interaction model here, in the Alexa config tool:
https://developer.amazon.com/edw/home.html#/skill

However, like you, I cannot generate an Utterances.txt. Could you assist @anjishnu?

**Comment by anjishnu** [comment]
you can put <b>sample_intent_schema.json</b> in place of INTENT_SCHEMA - that should work, I'll upload some sample utterances though.

**Comment by issachan** [comment]
Thank you. I tried that. I am very new to Python so it is probably just something I did wrong, but when I put the sample json in for that parameter it appeared to run, but didn't generate the file. Thank you

**Comment by anjishnu** [comment]
Just to clarify - the file should be generated in TRAINING_DATA_OUTPUT_LOCATION. It's just called utterances.txt by default.

**Comment by issachan** [comment]
Yes, thanks. I'm not at my PC at the moment, but I wrote basically this:
python -m ask.generate_training_data -i intent_schema.json -o E:\Development\Apps\Ask-Alexa-PyKit\
(I renamed the sample json).

And the instruction seemed to execute, but I didn't see any new file in the project folder.

**Comment by anjishnu** [comment]
I haven't tested this out on a PC at all - mostly on linux/mac/lambda - so I'm hoping I have used os.path.join everywhere. 

Can you please try: E:\Development\Apps\Ask-Alexa-PyKit\utterances.txt instead (i.e. put the name of the filename instead of the source directory).

I'll modify the code to work with both before the next release.

**Comment by issachan** [comment]
I'll give that a shot. Yes, I had to mess with paths a bunch to keep Python working properly. It was a pain. Not a fan of trying to dev python in windows. 
Thanks so much for your help.

**Comment by anjishnu** [comment]
If you remember any specific examples of code that failed due to path issues do let me know.

**Comment by issachan** [comment]
I was referring mostly to setting python and script paths in Windows. Your code when run via powershell works fine so far, other than this.

**Comment by anjishnu** [comment]
Added utterances.txt and updated instructions - closing this.

**Comment by issachan** [comment]
Thank you
