### ISSUE TITLE
README.md - Step 3 - No module named ask.generate_training_data

### ISSUE THREAD

**Issue by dundeemt** [anjishnu/ask-alexa-pykit#17]
version: 0.54
installed via: pip

```
$ python -m ask.generate_training_data -i intent_schema.json  -o .
/home/jlh/projects/alexa/bin/python: No module named ask.generate_training_data
```

The module generate_training_data only appears in the .5 branch and does not exist in the current version on pypi or the master branch.

**Comment by anjishnu** [comment]
Sorry about that - the name of the module changed - updated with the latest commit.
