### ISSUE TITLE
can this be used with chalice?

### ISSUE THREAD

**Issue by richiverse** [anjishnu/ask-alexa-pykit#27]
See https://GitHub.com/AWSlabs/chalice

**Comment by anjishnu** [comment]
I've never tried it - but I don't see why not - this code has no dependencies and is written in pure python - so just do something like - 

```
from lambda_function import alexa
# This loads the version of the alexa object which has been updated with annotations in the lambda_function code. 

@app.route("/")
def index():
    return alexa.route_request(app.current_request.json_body)

```

**Comment by richiverse** [comment]
Going to give it a try thanks!

**Comment by anjishnu** [comment]
Let me know if it works - then I'll close this out.
