### ISSUE TITLE
Issues deploying the sample app Basic on AWS

### ISSUE THREAD

**Issue by kfowlks** [anjishnu/ask-alexa-pykit#28]
module initialization error: 'VoiceHandler' object has no attribute 'default'

I'm getting the above error message when attempting to deploy the same sample AWS skill as a lambda.

**Comment by anjishnu** [comment]
Which version of the SDK did you use? i.e. how did you install it?

**Comment by kfowlks** [comment]
I used the release from master. I was able to get the _python_lambda_0.5_release_ release working. I noticed later on after the fact that you had some comments about master may be unstable in the README.md

**Comment by anjishnu** [comment]
Cool, good to know.
