### ISSUE TITLE
Handling session attributes

### ISSUE THREAD

**Issue by JoeGermuska** [anjishnu/ask-alexa-pykit#7]
I'm still pretty new to Alexa development, but I find the session management kind of weird. It seems as though you have to make a point to send back session attributes every time, which is counter to web programming models where you can trust the framework to manage that.

If you and other people using this code are interested, I'd like to talk about a good approach to handling it, and I'm happy to implement it and/or test it since session management seems likely to be part of what I need.

It would be easy enough to expose what comes in as `request['session']['attributes']` as something like `request.session` and just use it as a dictionary. But then in the current model, you'd need to remember to pass it to `create_response` -- some design which protected against forgetting to make that explicit seems worth looking for.

**Comment by anjishnu** [comment]
I think I understand what you are doing here (Took a look at your dev branch on your fork). Makes perfect sense.

**Comment by anjishnu** [comment]
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-interface-reference

And I feel like a moron now - looks like Amazon took care of handling that, more or less. So yes, it makes sense to just add those in.

**Comment by anjishnu** [comment]
Note, I'd suggest merging that change in quickly because I have a relatively large rework on the dev branch - which might change the name of the 'utils' file in the ask module.
